modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
    modId="usefulutilities"
    version="${file.jarVersion}"
    displayName="Useful Utilities"
    credits="LegionModding"
    authors="Made with <3 by LegionModding"
    description='''A mod which contains a bunch of useful utility blocks and items!'''
[[dependencies.usefulutilities]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.23,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulutilities]]
    modId="yalm"
    mandatory=true
    versionRange="[0.0.4,1.0.0)"
    ordering="NONE"
    side="BOTH"

